[[OpenFHE_int128]]
arch = "aarch64"
git-tree-sha1 = "72266f870e9abf1b25da585fc843bb19ba6b7706"
os = "macos"

    [[OpenFHE_int128.download]]
    sha256 = "ae6b243e05a76d0a42c52c1ba53e30074ca8e16763e432a118195c1d3fa7c6f3"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.5.0+0/OpenFHE_int128.v1.5.0.aarch64-apple-darwin.tar.gz"
[[OpenFHE_int128]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "541da41e2468690a6554b44494821f19c0e76d3c"
libc = "glibc"
os = "linux"

    [[OpenFHE_int128.download]]
    sha256 = "5bbcd4321f315a3ab3ed4299239fafd28559e70c3a45205a78f728963f1bc186"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.5.0+0/OpenFHE_int128.v1.5.0.aarch64-linux-gnu-cxx11.tar.gz"
[[OpenFHE_int128]]
arch = "aarch64"
git-tree-sha1 = "6a1f8da746f61230c9cef0044528bce58135af7c"
os = "freebsd"

    [[OpenFHE_int128.download]]
    sha256 = "53218975b6f7d2f28dffe9e1aa8389f9f725228b33127b5d7d433e32b00caf58"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.5.0+0/OpenFHE_int128.v1.5.0.aarch64-unknown-freebsd.tar.gz"
[[OpenFHE_int128]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47465494f4602da04db9c0259ea72ad70c6f5b34"
libc = "glibc"
os = "linux"

    [[OpenFHE_int128.download]]
    sha256 = "3f18ba55b7aabf43fbcf995fe1496a9f4dede0661c11dfbce0f4dbecc5865ceb"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.5.0+0/OpenFHE_int128.v1.5.0.riscv64-linux-gnu-cxx11.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
git-tree-sha1 = "58c60058a7834cfbc958e3375da8f57da0fcb6c4"
os = "macos"

    [[OpenFHE_int128.download]]
    sha256 = "153d77a777e8abe9397f7200bc53baa6fd95c34c476e163c3887e0718b0a675e"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.5.0+0/OpenFHE_int128.v1.5.0.x86_64-apple-darwin.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca1405a88925cff72434d66e44d95d37e29fbe82"
libc = "glibc"
os = "linux"

    [[OpenFHE_int128.download]]
    sha256 = "356f094ab266282f2181d7be1a2a5bdd71dc280db424f953e2fb518914ea036b"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.5.0+0/OpenFHE_int128.v1.5.0.x86_64-linux-gnu-cxx11.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
git-tree-sha1 = "3c96d1a3973ea706000f5103702148dfe77cca31"
os = "freebsd"

    [[OpenFHE_int128.download]]
    sha256 = "5dbe47e20852382e729f0774a6fec4873773da064a273f63e7b52d8eac663d14"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.5.0+0/OpenFHE_int128.v1.5.0.x86_64-unknown-freebsd.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb8b450313cf2cfbdc6b34de8b12567d63b269ba"
os = "windows"

    [[OpenFHE_int128.download]]
    sha256 = "bfa87186eb6f41d28811ae81aaaad8e09402d2a486dd2799b4b46e6ebd018663"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.5.0+0/OpenFHE_int128.v1.5.0.x86_64-w64-mingw32-cxx11.tar.gz"
