[[OpenFHE_int128]]
arch = "aarch64"
git-tree-sha1 = "0ef2647fae39a26c7fd99442ac36e36b90067ace"
os = "macos"

    [[OpenFHE_int128.download]]
    sha256 = "d4b36e6fb02ece306fa2629893a1207b18f1be021acda09f0d0a684dbc94679c"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.5.1+0/OpenFHE_int128.v1.5.1.aarch64-apple-darwin.tar.gz"
[[OpenFHE_int128]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc114c7bb88855dfbf397dab8f17034d34cf8b6e"
libc = "glibc"
os = "linux"

    [[OpenFHE_int128.download]]
    sha256 = "619ae35ce0fa4ba1f097d9146326833f70e43fca0073e49dcd0a9a7dade243f4"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.5.1+0/OpenFHE_int128.v1.5.1.aarch64-linux-gnu-cxx11.tar.gz"
[[OpenFHE_int128]]
arch = "aarch64"
git-tree-sha1 = "3187beb0de1ba86b440a78ff6c60824b67a1ec2c"
os = "freebsd"

    [[OpenFHE_int128.download]]
    sha256 = "9a8ae98b58164584ae153304ef0da7d006321bf1d952eb2e417f26b07e05697a"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.5.1+0/OpenFHE_int128.v1.5.1.aarch64-unknown-freebsd.tar.gz"
[[OpenFHE_int128]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be9d7b97ff93e32f555edcb0c718b012a6856455"
libc = "glibc"
os = "linux"

    [[OpenFHE_int128.download]]
    sha256 = "90981604cfa0bca339dc1115a7e1a56024ac9f088463fe237d1bc98a89bc36dd"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.5.1+0/OpenFHE_int128.v1.5.1.riscv64-linux-gnu-cxx11.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
git-tree-sha1 = "82826f8bfff28837f2116cd837e9cfb828334a7f"
os = "macos"

    [[OpenFHE_int128.download]]
    sha256 = "eea8173933b068a16fea80611febc8be32c543cac7ef295dc85fcc99e7e3a4ad"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.5.1+0/OpenFHE_int128.v1.5.1.x86_64-apple-darwin.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ce0ab3ef3af86b4aa6b12f21f4ebb01b5cbb245"
libc = "glibc"
os = "linux"

    [[OpenFHE_int128.download]]
    sha256 = "0c114b29adc2412a9af6a2a6d05886575d5945d0cc692a0ceb77320b5a0b89de"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.5.1+0/OpenFHE_int128.v1.5.1.x86_64-linux-gnu-cxx11.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
git-tree-sha1 = "6d86ea29c359fbbaa5b6ee934ea0cd966685a20f"
os = "freebsd"

    [[OpenFHE_int128.download]]
    sha256 = "57fe2e1327f9839626ed515c75656a7bbefc6de5601812cbd05828058e7e8c9d"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.5.1+0/OpenFHE_int128.v1.5.1.x86_64-unknown-freebsd.tar.gz"
[[OpenFHE_int128]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3f455421538f35005cab9b1aa8c91f7297b1eb1"
os = "windows"

    [[OpenFHE_int128.download]]
    sha256 = "f86b61e8fd4efc8c177cb2322134570dae7a57f95f70f80109124e11c499b5fd"
    url = "https://github.com/JuliaBinaryWrappers/OpenFHE_int128_jll.jl/releases/download/OpenFHE_int128-v1.5.1+0/OpenFHE_int128.v1.5.1.x86_64-w64-mingw32-cxx11.tar.gz"
